spring:
  datasource:
    username: root
    password: MadhurSinghal9555!
    url: jdbc:mysql://localhost:3306/ems
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:dialect: org.hibernate.dialect.MySQL5InnoDBDialect
